# Generated by Django 4.1.1 on 2022-12-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscritos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('fecha_insc', models.DateField(auto_now_add=True, verbose_name='Fecha de Inscripción')),
                ('hora_insc', models.TimeField(auto_now_add=True, verbose_name='Hora de Inscripción')),
                ('institucion', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('RESERVADO', 'RESERVADO'), ('COMPLETADA', 'COMPLETADA'), ('ANULADA', 'ANULADA'), ('NO ASISTEN', 'NO ASISTEN')], default='RESERVADO', max_length=10)),
                ('observacion', models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
