# Generated by Django 4.1.1 on 2022-12-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0003_alter_inscritos_fecha_insc_alter_inscritos_hora_insc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=20)),
            ],
        ),
    ]
